apiVersion: apps/v1
kind: Deployment
metadata:
  name: actions-runner-dev
  labels:
    app: actions-runner-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: actions-runner-dev
  template:
    metadata:
      annotations:
        container.apparmor.security.beta.kubernetes.io/docker: unconfined
      labels:
        app: actions-runner-dev
    spec:
      imagePullSecrets:
        - name: github-package-registry
      containers:
        - name: runner
          image: docker.pkg.github.com/urcomputeringpal/actions-runner-kubernetes/actions-runner-kubernetes-dev:latest
          imagePullPolicy: Always
          command:
          - /bin/sleep
          - "5678765456789876567898765"
          envFrom:
            - secretRef:
                name: actions-runner  
          env:
            - name: DOCKER_TLS_CERTDIR
              value: /certs
            - name: DOCKER_HOST
              value: tcp://localhost:2376
            - name: DOCKER_TLS_VERIFY
              value: "1"
            - name: DOCKER_CERT_PATH
              value: /certs/client
          volumeMounts:
            - name: docker-certs
              mountPath: /certs
        - name: docker
          image: docker:stable-dind-rootless
          args:
            - --experimental
          securityContext:
            procMount: Unmasked
            capabilities:
              add:
              - SETUID
              - SETGID
              - SYS_ADMIN
              - NET_ADMIN
          env:
            # - name: DOCKERD_ROOTLESS_ROOTLESSKIT_FLAGS
            #   value: 
            - name: DOCKER_TLS_CERTDIR
              value: /certs
          # TODO investigate rootless
          volumeMounts:
            - name: docker-storage
              mountPath: /var/lib/docker
            - name: docker-certs
              mountPath: /certs
      volumes:
        - name: docker-storage
          emptyDir: {}
        - name: docker-certs
          emptyDir: {}